### ISSUE TITLE
Unable to run the docker image

### ISSUE THREAD

**Issue by 007divyachawla** [morkin1792/CIWA#1]
docker build -t ciwa .
Sending build context to Docker daemon  183.8kB
Step 1/12 : FROM neo4j:enterprise
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by morkin1792** [comment]
Hi,
Sorry by late answer. I think that is problem in your environment. Please see this if the problem persists: https://forums.docker.com/t/docker-pull-results-in-request-canceled-while-waiting-for-connection-client-timeout-exceeded-while-awaiting-headers/73064
